# Auto-generated by grail — this is what Monty actually executes

resolved = target_node_id.strip() if target_node_id.strip() else await my_node_id()
dependencies = await graph_get_dependencies(resolved)
if not dependencies:
    result = f'No dependencies found for {resolved}'
else:
    lines = '\n'.join((f'- {node_id}' for node_id in dependencies[:30]))
    result = f'Dependencies for {resolved} ({len(dependencies)}):\n{lines}'
result