# Auto-generated by grail — this is what Monty actually executes

tag_list = [item.strip() for item in tags.split(',') if item.strip()]
correlation_id = await my_correlation_id()
existing = await kv_get('companion/chat_index') or []
existing.append({'correlation_id': correlation_id, 'summary': summary, 'tags': tag_list})
existing = existing[-50:]
await kv_set('companion/chat_index', existing)
result = f"Recorded summary with tags: {', '.join(tag_list)}"
result