# Auto-generated by grail — this is what Monty actually executes

MAX_PREVIEW = 500
MAX_OUTPUT = 2000
node = await graph_get_node(node_id)
if not node:
    result = f'Node {node_id} not found.'
else:
    current_source = node.get('text') or node.get('source_code') or ''
    previous_key = f'review:previous_source:{node_id}'
    previous_source = await kv_get(previous_key)
    if previous_source is None:
        await kv_set(previous_key, current_source)
        result = 'First review of this node. Source recorded for future comparisons.'
    elif previous_source == current_source:
        result = 'No changes since last review.'
    else:
        await kv_set(previous_key, current_source)
        result = f'Changes detected.\n\nPrevious ({len(previous_source)} chars):\n{previous_source[:MAX_PREVIEW]}\n\nCurrent ({len(current_source)} chars):\n{current_source[:MAX_PREVIEW]}'
result = result[:MAX_OUTPUT]
result