# Auto-generated by grail — do not edit

node_id: str

async def graph_get_node(target_id: str) -> dict:
    ...

async def kv_get(key: str) -> str | None:
    ...

async def kv_set(key: str, value: str) -> None:
    ...
