# Auto-generated by grail — this is what Monty actually executes

result = await send_message(to_node_id, content)
if result.get('sent'):
    message = f'Message sent to {to_node_id}'
else:
    reason = str(result.get('reason', 'unknown'))
    message = f'Message not sent to {to_node_id} ({reason})'
message