# Auto-generated by grail — do not edit

async def write_file(path: str, content: str) -> None:
    ...

async def propose_changes(reason: str = Constant(value='')) -> str:
    ...

async def my_node_id() -> str:
    ...
