# Auto-generated by grail — this is what Monty actually executes

nodes = await graph_list_nodes()
if not nodes:
    result = 'No nodes found.'
else:
    lines = []
    for node in nodes[:20]:
        lines.append(f"- [{node.get('node_type', '?')}] {node.get('full_name', node.get('name', '?'))} ({node.get('node_id', '?')})")
    result = f'Nodes ({len(nodes)} total, showing first 20):\n' + '\n'.join(lines)
result