# Auto-generated by grail — this is what Monty actually executes

MAX_ITEMS = 20
MAX_OUTPUT = 2000
nodes = await graph_query_nodes()
if not nodes:
    result = 'No nodes found.'
else:
    lines = []
    for node in nodes[:MAX_ITEMS]:
        lines.append(f"- [{node.get('node_type', '?')}] {node.get('full_name', node.get('name', '?'))} ({node.get('node_id', '?')})")
    result = f'Nodes ({len(nodes)} total, showing first {MAX_ITEMS}):\n' + '\n'.join(lines)
result = result[:MAX_OUTPUT]
result