# Auto-generated by grail — do not edit

async def graph_query_nodes(node_type: str | None = Constant(value=None), status: str | None = Constant(value=None), file_path: str | None = Constant(value=None), role: str | None = Constant(value=None)) -> list[dict]:
    ...
