# Auto-generated by grail — this is what Monty actually executes

option_list = [item.strip() for item in options.split(',') if item.strip()] if options else []
result = await request_human_input(question, option_list or None)
result