# Auto-generated by grail — this is what Monty actually executes

resolved = target_node_id.strip() if target_node_id.strip() else await my_node_id()
importers = await graph_get_importers(resolved)
if not importers:
    result = f'No importers found for {resolved}'
else:
    lines = '\n'.join((f'- {node_id}' for node_id in importers[:30]))
    result = f'Importers for {resolved} ({len(importers)}):\n{lines}'
result