# Auto-generated by grail — do not edit

insight: str

async def kv_get(key: str) -> object:
    ...

async def kv_set(key: str, value: object) -> None:
    ...

async def my_correlation_id() -> str | None:
    ...
