# Auto-generated by grail — this is what Monty actually executes

relationship = 'related'

def as_dict_list(value: object) -> list[dict[str, object]]:
    if not isinstance(value, list):
        return []
    result: list[dict[str, object]] = []
    for item in value:
        if isinstance(item, dict):
            result.append(item)
    return result
existing = as_dict_list(await kv_get('companion/links'))
already_linked = any((item.get('target') == target_node_id for item in existing))
if not already_linked:
    correlation_id = await my_correlation_id()
    existing.append({'target': target_node_id, 'relationship': relationship, 'correlation_id': correlation_id})
    existing = existing[-100:]
    await kv_set('companion/links', existing)
    result = f'Linked to {target_node_id} ({relationship})'
else:
    result = f'Already linked to {target_node_id}'
result