# Auto-generated by grail — this is what Monty actually executes

existing = await kv_get('companion/links') or []
already_linked = any((item.get('target') == target_node_id for item in existing))
if not already_linked:
    correlation_id = await my_correlation_id()
    existing.append({'target': target_node_id, 'relationship': relationship, 'correlation_id': correlation_id})
    existing = existing[-100:]
    await kv_set('companion/links', existing)
    result = f'Linked to {target_node_id} ({relationship})'
else:
    result = f'Already linked to {target_node_id}'
result