# Auto-generated by grail — this is what Monty actually executes

event_types_value: list[str] | None = [part.strip() for part in event_types.split(',') if part.strip()] if event_types.strip() else None
subscription_id = await event_subscribe(event_types_value, None, None, None)
message = f'Subscription {subscription_id} registered'
message