# Auto-generated by grail — do not edit

event_types: str

async def event_subscribe(event_types: list[str] | None, from_agents: list[str] | None, path_glob: str | None, tags: list[str] | None) -> int:
    ...
