# Auto-generated by grail — this is what Monty actually executes

node_type_value: str | None = node_type.strip() if node_type.strip() else None
role_value: str | None = role.strip() if role.strip() else None
status_value: str | None = status.strip() if status.strip() else None
file_path_value: str | None = file_path.strip() if file_path.strip() else None
agents = await graph_query_nodes(node_type_value, status_value, file_path_value, role_value)
result = str(agents)
result