# Auto-generated by grail — do not edit

node_type: str
role: str
status: str
file_path: str

async def graph_query_nodes(node_type: str | None, status: str | None, file_path: str | None = Constant(value=None), role: str | None = Constant(value=None)) -> list[dict]:
    ...
