# Auto-generated by grail — do not edit

target_node_id: str
edge_type: str

async def my_node_id() -> str:
    ...

async def graph_get_edges_by_type(target_id: str, edge_type: str) -> list[dict]:
    ...
