# Auto-generated by grail — this is what Monty actually executes

review_message = f'[Review/{severity.upper()}] {finding}'
submitted = await send_message(node_id, review_message)
if notify_user:
    await send_message('user', f'Review of {node_id}: {review_message}')
if submitted.get('sent'):
    result = f'Review submitted to {node_id} (severity={severity})'
else:
    reason = str(submitted.get('reason', 'unknown'))
    result = f'Failed to submit review to {node_id} ({reason})'
result